name: 'capstone'
version: '1.0.0'
config-version: 2

profile: 'capstone'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  capstone:
    metrics:
      +materialized: incremental
      +on_schema_change: "fail"
